version: "3.9"
services:

  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    volumes:
      - /opt/flame/config:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5005:5005
    secrets:
      - password
    environment:
      - PASSWORD_FILE=/run/secrets/password
    restart: unless-stopped

  caddy:
    build: ./caddy
    pull_policy: build
    container_name: caddy
    volumes:
      - /opt/caddy/config:/config
      - /opt/caddy/data:/data
      - /opt/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /opt/caddy/log:/var/log/caddy
    network_mode: host
    restart: unless-stopped

secrets:
  password:
    file: /opt/flame/password
