version: "3.9"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/prowlarr:/config
    ports:
      - ${PROWLARR_PORT}:9696
    restart: ${RESTART}

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/sonarr:/config
      - ${MEDIA_ROOT}/TV:/tv
      - ${DOWNLOAD_ROOT}:/downloads
    ports:
      - ${SONARR_PORT}:8989
    restart: ${RESTART}

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/radarr:/config
      - ${MEDIA_ROOT}/Movies:/movies
      - ${DOWNLOAD_ROOT}:/downloads
    ports:
      - ${RADARR_PORT}:7878
    restart: ${RESTART}

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/bazarr:/config
      - ${MEDIA_ROOT}/Movies:/movies
      - ${MEDIA_ROOT}/TV:/tv
      - ${DOWNLOAD_ROOT}:/downloads
    ports:
      - ${BAZARR_PORT}:6767
    restart: ${RESTART}

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT}
    volumes:
      - ${CONFIG_ROOT}/qbittorrent:/config
      - ${DOWNLOAD_ROOT}:/downloads
    ports:
      - ${QBITTORRENT_WEBUI_PORT}:${QBITTORRENT_WEBUI_PORT}
      - ${QBITTORRENT_PORT}:${QBITTORRENT_PORT}
      - ${QBITTORRENT_PORT}:${QBITTORRENT_PORT}/udp
    restart: ${RESTART}

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    group_add:
      - ${JELLYFIN_RENDER_GROUP}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_IP}
      - DOCKER_MODS=${JELLYFIN_DOCKER_MODS}
    volumes:
      - ${CONFIG_ROOT}/jellyfin:/config
      - ${MEDIA_ROOT}/TV:/data/tvshows
      - ${MEDIA_ROOT}/Anime:/data/anime
      - ${MEDIA_ROOT}/Movies:/data/movies
    ports:
      - ${JELLYFIN_PORT}:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    devices:
      - /dev/dri:/dev/dri
    restart: ${RESTART}

  filebrowser:
    image: filebrowser/filebrowser:s6
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/filebrowser/config:/config
      - ${CONFIG_ROOT}/filebrowser/database:/database
      - ${DOWNLOAD_ROOT}:/srv
    ports:
      - ${FILEBROWSER_PORT}:80
    restart: ${RESTART}

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
    volumes:
      - ${MEDIA_ROOT}/Audiobooks:/audiobooks
      - ${MEDIA_ROOT}/Podcasts:/podcasts
      - ${CONFIG_ROOT}/audiobookshelf/config:/config
      - ${CONFIG_ROOT}/audiobookshelf/metadata:/metadata
    ports:
      - ${AUDIOBOOKSHELF_PORT}:80
    restart: ${RESTART}

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/readarr:/config
      - ${DOWNLOAD_ROOT}:/downloads
      - ${MEDIA_ROOT}/Books:/books
    ports:
      - ${READARR_PORT}:8787
    restart: ${RESTART}