version: "3.9"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Bangkok
    volumes:
      - /srv/torrent/config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Bangkok
    volumes:
      - /srv/torrent/config/sonarr:/config
      - /srv/torrent/share/TV:/tv
      - /srv/torrent:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Bangkok
    volumes:
      - /srv/torrent/config/radarr:/config
      - /srv/torrent/share/Movies:/movies
      - /srv/torrent:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Bangkok
    volumes:
      - /srv/torrent/config/bazarr:/config
      - /srv/torrent/share/Movies:/movies
      - /srv/torrent/share/TV:/tv
      - /srv/torrent:/downloads
    ports:
      - 6767:6767
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Bangkok
      - WEBUI_PORT=8085
    volumes:
      - /srv/torrent/config/qbittorrent:/config
      - /srv/torrent:/downloads
    ports:
      - 8085:8085
      - 56535:56535
      - 56535:56535/udp
    restart: unless-stopped

  dim:
    image: ghcr.io/dusk-labs/dim:dev
    container_name: dim
    ports:
      - 8000:8000/tcp
    volumes:
      - /srv/torrent/config/dim:/opt/dim/config
      - /srv/torrent:/media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped